nhsx/standards-registry

.github/workflows/deploy-dev.yml
ckan/Dockerfile

Update charts to point to new image

Add custom ckan docker image

---

.github/workflows/deploy-dev.yml

Reverts nhsx/standards-registry#26

Revert "Fixing the chart path"

---

scraper/README.md
scraper/ingest/index.js
scraper/package-lock.json
scraper/package.json
scraper/test/specs/scraper.js
scraper/wdio.conf.js

Iterates over the standards lists for PRSB and NHS Digital and consumes basic standards metadata into a CSV

Add scraper script

---

ui/.eslintrc.js
ui/components/Dataset/index.js
ui/components/Tag/index.js
ui/pages/standards/[category]/[id].js
ui/schema/index.js

pass a status to Tag and style accordingly

---

Dockerfile-ckan

Reverts nhsx/standards-registry#34

Revert "[CKAN] Always reinstall ckan-scheming"

---

.github/workflows/build-and-test.yml
.github/workflows/deploy-test.yml

@roc I'm not sure this is going to work but I was hoping we could deploy using this approach?

Release to test using github releases!

---

ui/components/Filters/index.js

Adds two additional filters to the LHS of the UI. Fortunately query parsing is working in a way that means there's nothing else to do other than add the field names to the list of categories 🙌

[UI] Add category and status to filters

---

Dockerfile-ckan

This should install the CKAN page plugin so we can add static pages
as needed. It's very basic!

[CKAN] Add pages to CKAN

---

Dockerfile-ckan

Paster didn't work, hopefully passing in our `$CONFIG` variable will

[CKAN] run pages db init with config

---

ui/components/Search/style.module.scss
ui/package-lock.json
ui/package.json
ui/wdio.conf.js

[STAN-174] UI: more spacing around search input

---

ui/pages/index.js

[STAN-152] show short titles when available

---

ui/.gitignore
ui/schema/index.js

[UI] sentence case related standards label

---

ui/pages/index.js

[STAN-195] UI: update strap-line

---

.github/workflows/deploy-test.yml

Just to get us out the gates in terms of test runs

add workflow_run in a straight copy of dev

---

.github/workflows/build-and-test.yml
ui/components/FeedbackFooter/index.js
ui/context/content.js
ui/pages/standards/index.js

* Removes "all" from results copy
* Updates description text for browse index
* Feedback Footer updated

[STAN-235] UI: browse index changes

---

csv-exporter/.eslintrc.cjs
csv-exporter/.eslintrc.js
csv-exporter/.gitignore
csv-exporter/.prettierrc
csv-exporter/babel.config.json
csv-exporter/index.js
csv-exporter/package-lock.json
csv-exporter/package.json

* Adds a small sub-app which will hit the public CKAN `package_search` endpoint
* Adds authentication in order to show draft and private datasets
* adds them all to "test.csv" which can then be uploaded to e.g. google docs

[STAN-298] Take all datasets from CKAN and add to a CSV

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml
charts/ui/templates/deployment.yaml
charts/ui/values.yaml
ui/components/Analytics/index.js
ui/components/Layout/index.js
ui/components/index.js

If a tracking id is present, then embed Piwik analytics tracking into the site

Add PIWIK analytics tracking

---

ui/components/Link/index.js
ui/components/PhaseBanner/index.js
ui/components/PhaseBanner/style.module.scss

Homepage
Not the homepage
The feedback link is a mailto:standards.directory@nhsx.nhs.uk

Add BETA information to top banner

---

ui/components/PhaseBanner/index.js
ui/components/PhaseBanner/style.module.scss

make sure link colour works on homepage and on other pages

[STAN-271] make sure link works on homepage and elsewhere

---

ui/components/Expander/index.js
ui/components/Filters/index.js
ui/components/Layout/index.js
ui/components/Layout/style.module.scss
ui/components/Link/index.js
ui/components/Navigation/index.js
ui/components/Navigation/style.module.scss
ui/components/index.js
ui/pages/index.js
ui/pages/standards/[id].js
ui/pages/standards/index.js
ui/schema/index.js
ui/styles/Home.module.scss

See https://standardsportal.atlassian.net/browse/STAN-480 for details
This brings in all changes from the Prototype branch and then adds new changes on top of them.
* [STAN-481](https://standardsportal.atlassian.net/browse/STAN-481) Capital D in Standards Directory
* [STAN-484](https://standardsportal.atlassian.net/browse/STAN-484) Smaller font size RHS homepage
* [STAN-485](https://standardsportal.atlassian.net/browse/STAN-485) Decrease Space between Browse and blue section
* [STAN-486](https://standardsportal.atlassian.net/browse/STAN-486) Horizontal rules between sections
* [STAN-487](https://standardsportal.atlassian.net/browse/STAN-487) Darker grey dividers in sections outside of browse

[STAN-480] UI: Update homepage from prototype

---

ui/components/Filters/index.js

Now Care setting, Topic, Type.

Reorder filters on listings pages

---

csv-exporter/index.js
reader/parse/index.js
reader/write.js

**CSV-Exporter**
* When we export to csv, let's write a json file as well. It's much easier to re-import ([Write a json dump as well as csv](https://github.com/nhsx/standards-registry/commit/dc8fe5d71a1ee72fb2b36943c1d63ff2340cfc19))
**Dataset importing**
* `business use` is no more, long live `topic`
* Add auth headers to dataset search requests so we can retrieve hidden/unpublished datasets as well

Smol import improvements

---

reader/write.js
ui/components/Dataset/index.js
ui/components/Dataset/style.module.scss

Also includes migration changes

[STAN-493] Add nationally mandated

---

ui/components/Dataset/index.js

* always delete mandated, add back if selected

Show mandated, or ignore field 

---

ui/components/Dataset/index.js

[STAN-450] Add in help message for no search results

---

ui/helpers/api.js

* Added to solr search query - fuzzy search title to match things like alergy

Feature fuzzy search

---

docs/index.md
docs/reports/2022-04-21.md

First attempt to push the report via github

Report 2022-04-22

---

docs/reports/2022-04-21.md

First attempt to push the report via github

final final url for now and remove square brackets

---

ui/components/Dataset/index.js
ui/pages/index.js
ui/test/specs/home.js
ui/test/specs/standards/list.js

* will fail if recents on the homepage drop below 3
* will fail if there are not 10 results on the directory homepage

[test] Check recents and directory have standards

---

docs/index.md
docs/reports/2022-04-28.md

I'm just putting this in. I might want to add a goal for this week.

weekly report 28 04 2022

---

ui/components/FeedbackFooter/index.js
ui/components/FeedbackFooter/style.module.scss
ui/components/PhaseBanner/index.js
ui/components/index.js
ui/pages/index.js
ui/pages/search-results.js
ui/pages/standards/index.js

* Added feedback footer with survey link to homepage, and search results/directory listing
* Added survey link to header

Feature - feedback footer

---

ui/components/Tag/index.js

Re-updated now that record types have updated again

update tag colour map

---

ui/components/Dataset/index.js
ui/components/Layout/index.js
ui/components/Navigation/index.js
ui/context/content.js
ui/cypress/integration/home.js
ui/cypress/integration/standards/list.js
ui/pages/index.js
ui/pages/search-results.js
ui/pages/standards/index.js
ui/schema/index.js

This is all @karypun's work I'm just here to hijack it and make tests pass

Content update update

---

ui/components/Dataset/index.js
ui/components/Dataset/style.module.scss
ui/components/FeedbackFooter/index.js
ui/components/Flex/style.module.scss
ui/components/Search/index.js
ui/package-lock.json
ui/pages/index.js
ui/styles/Home.module.scss

* homepage grid to accommodate variable heading lengths
* switches to single column below tablet widths
* various small content updates

[STAN-603] Content updates, homepage Grid

---

package-lock.json
package.json
ui/package-lock.json
ui/package.json

looks like the husky commit hook wasn't working for anyone else!
Install husky at the same level as the .git repository in order for hooks to run

add husky to project root

---

docs/index.md
docs/reports/2022-05-26.md

Ready I think for this week's weekly report

Report26052022

---

ui/components/Layout/index.js
ui/components/Page/index.js
ui/components/PhaseBanner/style.module.scss
ui/components/Search/index.js
ui/components/Snippet/index.js
ui/context/content.js
ui/pages/_document.js
ui/pages/index.js
ui/pages/search-results.js
ui/pages/standards/[id].js
ui/pages/standards/index.js

[STAN-624](https://standardsportal.atlassian.net/browse/STAN-624)
* Updates the content context provider to take a page title and merge with standards directory title.
* All pages should now have a title
[STAN-622](https://standardsportal.atlassian.net/browse/STAN-622)
[STAN-625](https://standardsportal.atlassian.net/browse/STAN-625)
[STAN-626](https://standardsportal.atlassian.net/browse/STAN-626)
[STAN-623](https://standardsportal.atlassian.net/browse/STAN-623)

Accessibility Changes

---

ui/components/Layout/index.js

[STAN-482] add cookies to footer

---

.husky/pre-commit
.prettierrc
reader/lib/write/index.js
reader/package-lock.json
reader/package.json
reader/write-json-to-ckan.js

* adds a way to take an export of all records from one CKAN instance and write them to another
* updates writeToCKAN to accept json instead of a file
* adds "fun" ansi logo to script

Add an export/import tool for ckan json

---

ui/components/Layout/index.js
ui/components/Navigation/index.js
ui/components/Search/index.js
ui/cypress/integration/home.js
ui/cypress/integration/standards/list.js
ui/pages/index.js
ui/pages/standards/index.js

- update content on the homepage to match miro updates https://miro.com/app/board/uXjVOy1WyKs=/

[STAN-762] homepage changes

---

ui/pages/search-results.js

[STAN-766] update search results description para

---

ui/package-lock.json
ui/schema/index.js

* Updated standard type descriptions on individual listing page in line with new provided content

Content - STAN/785 - update standard type descriptions

---

ui/components/FilterSummary/FilterSummary.module.scss
ui/components/FilterSummary/index.js
ui/package-lock.json

* Updated filter summary to display all filters with ANDs in between, apart from type which appears on a new line with an IN before

Bugfix - move filter summary

---

ui/components/Breadcrumbs/style.module.scss
ui/components/PhaseBanner/style.module.scss

[STAN-841] margin and bg changes for the header

---

ui/components/Expander/Expander.module.scss
ui/components/Expander/index.js
ui/components/Filters/Filters.module.scss
ui/components/Filters/index.js
ui/components/ResponsiveTable/index.js
ui/pages/roadmap.js
ui/schema/index.js

* Updated roadmap with design tweaks
https://miro.com/app/board/uXjVOja0Ln4=

Tweaks - roadmap

---

ui/components/FilterSummary/index.js

* Dont return undefined when fetching data - this causes a UI error

Bugfix - dont throw undefined

---

ui/components/Table/style.module.scss

* Updated padding for pseudo headers on small screen

Tweak - roadmap mobile

---

ui/components/Dataset/index.js
ui/components/ResponsiveTable/index.js
ui/components/Table/index.js
ui/components/Table/style.module.scss
ui/helpers/api.js
ui/pages/roadmap.js
ui/schema/index.js

* Updated roadmap sort labels
* Removed "default" roadmap sort, default is name A-Z
* Updated roadmap table header sort to use sort icons
* Updated published standards to use last created as default sort

Tweaks - roadmap sort

---

ui/cypress/e2e/home.cy.js
ui/pages/index.js
ui/pages/standards/index.js

Revised service name and tagline:

[STAN-865] switch header and intro

---

ui/components/PhaseBanner/index.js

[STAN-871] update banner text

---

ui/components/FilterSummary/index.js

quieten unique key error in filter summary

---

ui/components/Analytics/index.js
ui/components/Cookies/index.js
ui/components/Navigation/index.js
ui/cypress/e2e/home.cy.js
ui/cypress/e2e/static-page.cy.js
ui/pages/index.js

[STAN-905] allow cookie rejection

---

ui/components/PhaseBanner/index.js

Now reads: BETA This is a new service. Your feedback will help us improve it.

Content - updated content on phase banner

---

ui/pages/future-standards.js
ui/pages/roadmap.js

* Added holding page for roadmap

Feature - roadmap holding page

---

ui/pages/index.js

* Updated all links to standards on the homepage to link to current-standards

Bugfix - homepage standards links

---

ui/components/Layout/index.js

* Updated email link in footer to england.interop.standards@nhs.net

Bugfix - footer email

---

.github/workflows/deploy-dev.yml
.github/workflows/helm-deploy-ui.yml
ui/Dockerfile
ui/components/Layout/index.js

- In order to confirm we own each domain to google, we can attach these site codes
- Site codes to be added per environment in github

[STAN-886] Add google site code meta tag

---

ui/pages/site-map.js

* Added site-map page
* Added links to pages with urls pulled from ckan pages

Feature - dynamic sitemap

---

ui/pages/404.js
ui/pages/500.js
ui/pages/current-standards/index.js

* Added 404 page and 500 page (500 is used for client side errors as well as server)

Feature - error pages

---

ui/helpers/api.js

* Updated to use axios which throws errors on bad status codes
* Catch errors and log to console.error

Feature - API Errors

---

ui/components/FeedbackFooter/index.js
ui/components/PhaseBanner/index.js
ui/schema/index.js

[STAN-740] add "opens in new window" to new window links

---

ui/components/CookiesTable/index.js
ui/components/Table/index.js
ui/components/index.js
ui/pages/[page].js

* Added cookies table component
* Added cookies content from prod/jira
* Removed boilerplate code

Feature - cookies table

---

ui/components/Breadcrumbs/index.js
ui/cypress/e2e/standards/list.cy.js

* updated breadcrumb component to ignore the URL hash

Bugifx - hash link breadcrumbs

---

ui/public/sitemap.xml

* Adding an auto-generated sitemap 
* Should be available at /sitemap.xml
* Means we can ping the sitemap https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#addsitemap

[STAN-976] add sitemap to public folder

---

ui/pages/search-results.js

We decided to keep search titles, so this should add them back in.
See comment thread in
https://standardsportal.atlassian.net/browse/STAN-941

[STAN-941] add search title back into results

---

ui/components/DatasetSchema/index.js

Some small updates to individual dataset schema.org annotations

update standard schema representation

---

ui/components/DatasetSchema/index.js
ui/cypress/e2e/schema.org.cy.js

Fix the &quot; escaping added by next/head

[STAN-1104] fix schema escaping with dangerouslySetInnerHTML

---

ui/components/Cookies/index.js
ui/components/Layout/index.js
ui/cypress/e2e/home.cy.js
ui/pages/current-standards/index.js
ui/pages/index.js
ui/pages/search-results.js
ui/pages/site-map.js

* Updated NHS Standards Directory to NHS Data Standards Directory

Feature - updated service name

---

ui/schema/index.js

Fixes stage values coming out as e.g. "Draft-in-progress"
Now:

[STAN-1087] sentence case status values

---

ui/components/Breadcrumbs/index.js
ui/components/Layout/index.js

[STAN-1055] if we have a dataset, use its title in the breadcrumb

---

ui/components/FilterSummary/index.js
ui/cypress/e2e/standards/list.cy.js
ui/schema/filters.js
ui/schema/index.js

* Updated logic so first connector is always "and"

Bugfix - filter summary and/or

---

ui/schema/index.js

* Various content updates for standards page
* Added new section with link to documentation

Content - Standards page content updates

---

ui/cypress.config.js
ui/cypress/e2e/a11y-basic.cy.js
ui/cypress/e2e/home.cy.js

* also adds in new `'attribute-allowed-values'` rule to safeguard against errors arising from nextjs default markup

Move html validate config to install step

---

report-generator/README.md
report-generator/generate_report.py

Modifying the README and the script to give future report writers a chance

Add dependencies to report generator README

---

docs/index.md
docs/reports/2022-12-15.md

Normally weekly report - I'm getting a "can't automatically merge" message. Don't really know what the means.

This week's weekly report - my last
