Dockerfile-ckan

What
----
Now that https://github.com/Marvell-Consulting/ckanext-extrafields/pull/1 has landed,
extrafields is essentially a shell we can use to commit schema information
ready for use by the scheming plugin.
Here we're adding the scheming plugin and then pointing the
`ckan config-tool` to set the dataset reference to
`ckanext-extrafields/ckanext/extrafields/ckan_dataset.yaml`
Why?
----
The [ckan scheming](https://github.com/ckan/ckanext-scheming) plugin provides an
easily configurable way of mofifying CKAN schemas, and making
representations of those schemas available in CKAN forms. Unless we come
up against some very custom fields, this is a good way to get going with
most of the basic needs for the registry form fields and data structure.

[CKAN] Use scheming plugin

---

Dockerfile-ckan

* A brute force method to ensure that the latest
ckanext-scheming changes are pulled down and that `setup.py`
is called
* This is to ensure changes we push to ckan-scheming are
honoured by each deploy
* We could/should eventually define a way to ensure deploys
are idempotent, as well as a separate update job, but for
now they're being lumped together here

[CKAN] Always reinstall ckan-scheming

---

ui/components/Filters/index.js
ui/helpers/api.js
ui/helpers/getPageProps.js

Should mean we can send both fq style queries and our usual q, sort, pagination queries to CKAN.
TODO: UI rests on request time, making it laggy

[UI] Compose queries for CKAN

---

ui/schema/index.js

* Sometimes the references are going to be links
* Parsing markdown keeps it consistent with the other fields

[UI] Add markdown parsing for Related Standards

---

ui/components/Link/index.js
ui/components/Model/index.js
ui/schema/index.js

* Update the 'no value' generic text for each category
* Merge documentation and documentation link 
* include generic text for each documentation link
* update `Link` to include options to open in a new window
Things we say when we have no value:

[UI] Update standard listing formatting

---

ui/components/FeedbackFooter/index.js
ui/components/index.js
ui/pages/standards/[id].js
ui/pages/standards/index.js

We have a feedback [footer in the prototype](https://nhs-standards-registry.herokuapp.com/v5/standard-mental-health). This just adds the same thing to our frontend.
Additionally I've removed the Updates/Feedback panels as they aren't in scope for MVP
On standards index page:
On Standard entry page:

[UI] Add feedback footer

---

ui/components/Dataset/index.js
ui/context/content.js
ui/context/query.js
ui/pages/standards/index.js

- pagination wasn't working because it worked on the assumption that `getQuery` would also potentially return an update based on query props, but I think I broke that when we were working on filters
- Also removes duplication of results summaries

[UI] Fix pagination

---

Dockerfile-ckan

Now that https://github.com/Marvell-Consulting/ckanext-scheming/commit/899a91a6de08e29d722064f11e7bcac716bd3ac2 has landed, we should be able
to pull in org schemas in CKAN. At the moment the only addition we're
making is to add contact email addresses to orgs, but in the future we
can extend to any number of additional fields using the plugin

[CKAN] Add org schemas to CKAN

---

Dockerfile-ckan

I thought you could bundle config-tool actions, but that seems to fail in docker. Put them on a new line instead

[CKAN] put each config action on a new line

---

ui/schema/index.js

In CKAN we're using `reference_code`, but I forgot to update this on the front end

[UI] approval code is now reference code

---

Dockerfile-ckan

Let's try passing in the config where possible, and see if paster does any better with finding the db connection. If this doesn't work we can try the more idiomatic version of initialisation in CKAN 2.9 e.g.
```
RUN ckan --config "$CONFIG" pages initdb
```

[CKAN] init pages db using paster

---

ui/components/MarkdownBlock/index.js
ui/components/index.js
ui/helpers/api.js
ui/pages/[page].js
ui/pages/index.js

Here we're querying `action/ckanext_pages_list` to bring back our new
static `pages` content from CKAN.
Preview tiles are rendered into the homepage and ordered by section.
This is done using js on the frontend, seeing as the Pages ckan plugin
does not have good native support for querying by new fields (see
[discussion here](https://gitter.im/ckan/chat?at=61d6fc867842bd3ca931c069)).
In order to make this work locally I've added a blank page for the
directory itself, with the specific url slug "standards". This means the
tile is added but clicking into it will hit our specific '/standards'
controller and not the [pages] one.

[UI] Add pages to frontend

---

ui/schema/index.js

This is a mailto: link
We say "Contact information not yet provided"

[STAN-146] UI: show contact email on standards page

---

ui/components/Layout/index.js
ui/pages/index.js

Before: search is visible top right and in the centre
After: only one search on homepage
Nav search still shows up in all other pages

[UI] hide search on homepage

---

ui/components/Grid/index.js
ui/components/Search/index.js
ui/components/Search/style.module.scss

Don't allow tiles to spread the full width of the display column, even if they're alone on a row.
Fixes an issue in which the search component was escaping the bounds of the mobile viewport, also constrains the icon and hover/focus states of the component.

[UI] Homepage and search updates

---

ui/components/Breadcrumbs/index.js
ui/components/Breadcrumbs/style.module.scss

The NHS toolkit [hides breadcrumbs until the browser width is at or above tablet width](https://github.com/nhsuk/nhsuk-frontend/blob/master/packages/components/breadcrumb/_breadcrumb.scss#L47-L51).
For us the breadcrumbs were hidden but a white background was still visible.
Here we're overriding this setting to display breadcrumbs at all sizes.

[STAN-173] UI: show breadcrumbs at all sizes

---

ui/pages/[page].js

**Before**
Content ranges across the whole page, mismatching the [v5 proto](https://nhs-standards-registry.herokuapp.com/v5/what)
**After:**

[STAN-183] UI: wrap static page content in 2/3rd column 

---

ui/context/query.js

When we select filters, we're passing down a `Link` command to the router, which has accepts a [`TransitionOptions interface`](https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/router/router.ts#L53-L57): 
```
{
shallow?: boolean;
locale?: string | false;
scroll?: boolean;
}
```
Here we're setting `scroll` to `false` to prevent filter selections sending the user to the top of the page.
Cf. https://stackoverflow.com/questions/65902664/next-js-router-push-without-scrolling-to-the-top?answertab=votes#tab-top

[STAN-175] UI: stop filter selections scrolling to the top

---

ui/components/Dataset/index.js
ui/components/Dataset/style.module.scss
ui/components/Flex/index.js
ui/components/Flex/style.module.scss

Additionally, I've tried to remove margin at the bottom of each listing, to try and match with what we have in the prototype. It's a first pass and (as with everything, really) can be modified based on whatever @karypun thinks

[STAN-171] UI: align updated info to the right

---

ui/components/Dataset/index.js
ui/context/content.js

When no filters/search is added, we'll now show summary information about the number of listings we have 
We still show this information if we pass a search term

[STAN-170] UI: show number of standards on index 

---

ui/components/Layout/index.js
ui/components/Layout/style.module.scss
ui/components/Search/style.module.scss

At all sizes, ensure the logo and the service name remain
on the same line. This means adjusting the spacing between
logo and service name to be the same from tablet upwards.
**Wide desktop**
**Desktop**
**Tablet**
**Mobile**

[UI] keep logo and service name on same line

---

ui/helpers/api.js

At the moment when we select filters, they send an `AND` operator to the CKAN API. If we select *Business Use* `Appointment / scheduling` and `Referrals`, that means we'll only get results if records contain *both* of those category selections.
This change will modify this behaviour so that any records which contain `Appointment / scheduling` *OR* `Referrals` will be returned.
In addition, different categories will also be joined by the `OR` operator. Meaning e.g. *Business use* and *Care setting* combinations will produce a greater number of results, rather than refining to a smaller subset.
See for example these two different queries:
[(Care setting = Dentistry AND Community) AND (Business use = Continuity)](http://a864b7b77f8e140858ab710899b7ed73-1561736528.eu-west-2.elb.amazonaws.com:5 …

Filtering: switch from AND to OR operators

---

ui/components/Grid/index.js
ui/components/Paragraph/index.js
ui/components/index.js
ui/pages/standards/[id].js
ui/schema/index.js

**New!** 
What this status means Details:
**Banished!**
Tag removed on heading caption
**Slightly altered!**
Reference code dropped down into Assurance section. (There's more work to be done here but we should talk about the best way of updating assurance information)

[STAN-235] UI: update listing page update

---

ui/components/TableOfContents/index.js
ui/components/index.js
ui/package-lock.json
ui/package.json
ui/pages/[page].js

We've added the [option to add a table of contents to Pages in CKAN](https://github.com/Marvell-Consulting/ckanext-pages/commit/b3607064e0c5235cab31b154d42b00cd33b2c29b) via the Pages Plugin.
This is the corresponding front-end update. It's barebones, using [`mdast-util-from-markdown`](https://github.com/syntax-tree/mdast-util-from-markdown) to parse markdown from CKAN into an AST and then render that out as an unordered list. Depth of headings corresponds to depth of `<ul>`.

[STAN-245] Dynamically generate table of contents for static pages

---

Dockerfile-ckan

* Adds page tracking: https://docs.ckan.org/en/2.9/maintaining/tracking.html
* Sets up cronjobs directly on the ckan machine, though we can probably update this to use kubectl CronJob deployments in the future
* Search Indexes and page tracking information is rebuilt hourly

[CKAN] Add cronjobs to dockerfile

---

Dockerfile-ckan

A quick followup on the cron job: cron is not on the ckan image, but crontab is. Let's just use crontab

[CKAN] use crontab as cron is not on the image

---

Dockerfile-ckan
charts/ckan/templates/ckan-cli-cronjob.yaml
charts/ckan/values.yaml

- For each cronjob run a blank keitaro ckan image and pass a command
- keep 2x failing pods, remove if successful
- should run search index rebuilds nightly and [CKAN page view tracking every hour](https://docs.ckan.org/en/2.9/maintaining/tracking.html)

[STAN-410] run cronjobs popularity and search

---

.github/workflows/deploy-dev.yml

Now that we have some versions of our own [ckan helm chart](https://github.com/Marvell-Consulting/ckan-helm-chart) published (see https://api.github.com/repos/Marvell-Consulting/ckan-helm-chart/releases for more) we should be able to use this to deploy dev, and hopefully get [cronjob-cli](https://github.com/Marvell-Consulting/ckan-helm-chart/blob/main/charts/ckan/templates/cronjob-cli.yaml) running

[STAN-410] try a direct swap to marv helm chart for ckan deploy

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml

Deploying using [our version of the keitaro ckan helm chart](https://marvell-consulting.github.io/ckan-helm-chart/) seems to have done what we were after in dev by adding some additional cron jobs:
Here we're updating `test` and `prod` deployments to do the same thing

[STAN-410] Use marv charts in test and prod

---

.github/workflows/build-and-test.yml
ui/components/Filters/index.js
ui/pages/index.js
ui/schema/index.js
ui/test/specs/standards/list.js
ui/wdio.conf.js

We've updated the schema to show `Topic` instead of `Business Use` [here](https://github.com/Marvell-Consulting/ckanext-scheming/commit/2a433a23fe3c6f37fd1964f017767483b3ae8bb0) 
Now we can respond to it in the frontend

[STAN-488] Change Business Use to Topic

---

ui/pages/[page].js

Instead of throwing a 500 error about `pageData` not being serialisable as JSON, instead return a 404.

Return a 404 page for pages which don't exist

---

ui/components/Dataset/index.js
ui/context/query.js
ui/helpers/api.js

Supports sorting the list of all standards by best search match, last updated timestamp, or name. Including:
* Add option to not create new history entry when sorting
* If there's a `sort` value defined in the query string as a string then don't try to manipulate an object to a string
* Only show `Relevance` as a sort option if there's a search term defined

Add sort menu to standards listing

---

.github/workflows/build-and-test.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml

Sends a slack message to #developers when a PR build fails or on any complete deployment irrespective of status.

Add alerting into Slack for build statuses

---

ui/components/Layout/index.js
ui/components/Search/index.js
ui/components/Search/style.module.scss
ui/pages/index.js
ui/pages/search-results.js
ui/pages/standards/index.js

[Adds "location" to search for styling in context](https://github.com/nhsx/standards-registry/commit/e5433c93c7a807ea533b02bb52c29076dc87c2a9)
* `location` can now be passed to `Search`
* means it works in its different contexts (Home, Directory, and Navigation bar)
* Rough and ready swapping between "Search" button and Icon button
* Lots of `Layout` wrangling to remove search from nav when it's rendered
lower in the page, which I'm not thrilled with, but seems the way for now
**Browse Context**
**Nav context**
**Homepage @mobile**
**Homepage**

[STAN-491] Add large search bar to directory pages

---

ui/components/Tag/index.js
ui/helpers/api.js
ui/schema/index.js

* Update the `Tag` component to handle types instead of statuses
* Add a quick and dirty label mapper into the API fetching code to convert the old labels to the new ones

STAN-496 standard type tags

---

Dockerfile-ckan
csv-exporter/handler.js

Uses our latest and greatest CKAN plugin: https://github.com/Marvell-Consulting/ckanext-download-csv-button
This is where the ~hacking~ [magic happens](https://github.com/Marvell-Consulting/ckanext-download-csv-button/blob/main/ckanext/download_csv_button/templates/package/search.html#L8)

[STAN-399] Add a CSV download button to dataset page

---

.github/workflows/deploy-dev.yml

* Uses serverless's github action https://github.com/serverless/github-action 
* debugging is on for now `SLS_DEBUG`
* attempts to use the 16.x version of lambda, though we'll see how that goes (at least it should definitely deploy to 14.x)

[STAN-534] Add csv exporter function deployment

---

.github/workflows/deploy-dev.yml

Otherwise the notification may be triggered as a success when the serverless deploy failed.

Wait for serverless to deploy before running integration tests

---

.github/workflows/deploy-dev.yml

The struggle with the serverless config living
outside the root of the folder is  detailed [here](https://github.com/serverless/github-action/issues/53\#issuecomment-1059839383)
The github action _should_ respect sub folders, though we can also force it run from the correct folder

[STAN-534] force directory in serverless args

---

.github/workflows/notify-fail.yml

`Build failed` is a pretty useless message.

Use default message for failure notification

---

ui/Dockerfile

Pass in flag to ensure swc binary is downloaded during the dev build process
See: https://nextjs.org/docs/messages/failed-loading-swc
> you might need to allow optional packages to be installed by your package manager (remove --no-optional flag) for the package to download correctly.
Failing build:
https://github.com/nhsx/standards-registry/runs/6368264350?check_suite_focus=true#step:6:70

pass `--include-optional` flag in dockerfile 

---

ui/components/Dataset/index.js
ui/components/Expander/index.js
ui/components/FilterSummary/index.js
ui/components/Filters/index.js
ui/cypress/integration/standards/list.js

* Type no longer in expander to avoid unnecessary click:
* removes open/close all link
**before**
**after:**
* only open expanders with selected options on page load (fixes as clash in which you could open an adjacent expander by clicking the options in another one)
* Temporarily hacks "type of standard" to "type", we will change this in ckan
* Mandated in england content change

Small filter changes

---

ui/components/Expander/Expander.module.scss
ui/components/FilterSummary/index.js
ui/components/Filters/Filters.module.scss
ui/components/Filters/index.js
ui/components/Search/index.js
ui/cypress/integration/home.js
ui/cypress/integration/standards/standard-page.js
ui/cypress/integration/static-page.js
ui/cypress/support/commands.js

* Removing the router 'navigate' option from search broke search from the homepage
* this adds it back in and also fixes an in issue in which passing a blank search from the homepage would cause a search for the string 'undefined' (now it searches for `""`, bringing back all results)
**Filter updates**
* filter headings removed unless you have several selected and _then_ select a `Type` (we write "in" for that)
* expander icons aligned with headings
* When clicking "mandated" alone we no longer get two lines across the filter summary section

[STAN-557] Search and Filter fixes

---

ui/.eslintrc.js
ui/components/Analytics/index.js
ui/components/Dataset/__tests__/dataset.test.js
ui/components/Dataset/index.js
ui/components/Filters/index.js
ui/jest.config.js
ui/package-lock.json
ui/package.json
ui/test/babel.config.js
ui/test/jest/__mocks__/styleMock.js
ui/test/jest/setup.js

* Dates are now formatted `'d MMM yyyy'`, e.g. `4 May 2022`
* Adds [Jest](https://jestjs.io/) for unit testing 🃏 
* Adds more linting: https://nextjs.org/docs/basic-features/eslint#eslint-plugin
* Adds linting rules for tests and the [jest eslint plugin](https://www.npmjs.com/package/eslint-plugin-jest)
* Respond to linting errors, mainly around our use of hooks
* Tests are run in jsdom with a view that we'll probably want that for component testing further down the road 
* Jest borks when dealing with the style preprocessing next does, so we have a [style mock for tests](https://github.com/nhsx/standards-registry/blob/8d2c2b4bddc01687d7b2ad7bf7a803817751e349/ui/test/babel.config.js)
* Next reverts from using SWC for compilation if it detects the presence of any babel config. Jest relies …

[STAN-602] New date format, with tests!

---

ui/.prettierignore
ui/package.json

* `pretty-quick` only runs on files that are changed since the last commit, so won't work in CI by definition. Replace prettier implementation in `npm test` with `prettier`.
* `.prettierignore` file needs to be in the UI directory to be read correctly by that command.

Fix prettier test run

---

ui/components/Dataset/index.js
ui/components/Filters/Filters.module.scss
ui/components/Filters/index.js
ui/components/Form/CheckboxGroup.js
ui/components/Layout/index.js
ui/components/Search/index.js
ui/components/Select/index.js

This PR is a collection of responses to the use of the [ARC accessibility toolkit](https://www.tpgi.com/arc-platform/arc-toolkit/)
Fixes: 
* [STAN-627 empty legend](https://standardsportal.atlassian.net/browse/STAN-627)
* [STAN-628 accessible name for select](https://standardsportal.atlassian.net/browse/STAN-628)
[add labels to search button when using icon](https://github.com/nhsx/standards-registry/commit/4e3b76ca71aae05ded58df483b7f1a54b4bdfd74)
[ensure label corresponds to select](https://github.com/nhsx/standards-registry/commit/bc8dc269d7b3ad6c849debb606e6917c718e32d1)
[swap out heading for label in filter select](https://github.com/nhsx/standards-registry/commit/866f876c25425dedd9d949b07c465d0a246fde40)
[set SVG focusable to …

More accessibility fixes

---

ui/components/MarkdownBlock/index.js
ui/package.json
ui/pages/[page].js

* just use `react-markdown` for rendering markdown
* remove unused `marked` and `body-parser` dependencies

[STAN-631] simplify markdown rendering

---

ui/components/Search/style.module.scss

* Updates the search button styles to have a yellow background with black text when clicked.
* All states should have sufficient contrast
* Also checked the feedback link, which seems to respond as expected 
Hover state
Selected
input focused
feedback link focused
Icon focused

[STAN-519] simplify search button style states

---

ui/components/Grid/index.js
ui/components/Layout/index.js
ui/components/Search/index.js
ui/components/Search/style.module.scss

Before
After
Matching up to the way search is done in the nav on NHS service manual

[UI] Redo header nav search

---

ui/pages/search-results.js

- before we'd use the same title for the page html title *and* for the results heading
- now we just show "Search results" in the search heading

Remove title from search results heading

---

ui/components/Layout/index.js
ui/components/Layout/style.module.scss

Adds in our new footer links
**mobile**
**tablet-ish**
**desktop**

[STAN-616] Add new footer links

---

ui/components/FilterSummary/FilterSummary.module.scss
ui/components/FilterSummary/index.js

- users can now tab into buttons to remove filters
- markup and aria labels based on https://weboverhauls.github.io/demos/chips/

[STAN-726] Switch filter summary markup for a11y

---

ui/components/Pagination/index.js
ui/context/query.js

- uses Next `<Link>` component and defers routing behaviour to Next
- generates anchor links with hrefs and aria labels, meaning keyboard
navigation/tab focus is possible

[STAN-729] Change pagination to use Link component

---

ui/components/Dataset/index.js
ui/components/ReviewDates/index.js
ui/components/Tag/index.js
ui/schema/index.js

- Status now wrapped in `<Tag>` component
- Tag removed from type
- Next review date removed

[STAN-768] standards listings and status tags

---

ui/components/Model/index.js
ui/components/Model/style.module.scss
ui/cypress/integration/standards/list.js

Before: 
use of tables, accessibility sad:
After:
Use data lists/definitions organised by grid, accessibility less sad:
The layout and style should be almost identical between builds, though there is less markup in use now. 
Aside: we can likely remove our `Table, Thead, Tbody, Tr, Td` components now

[STAN-734] switch from tables to description lists

---

ui/cypress/e2e/standards/list.cy.js
ui/cypress/plugins/index.js
ui/cypress/support/custom.js
ui/cypress/support/e2e.js
ui/package-lock.json
ui/package.json

* Adds cypress-axe for a11y testing
* Adds support for logging advisories to a table
* Skips failures for now.
A11y advice looks like this:

[STAN-829] Add cypress-axe, check a11y in one test

---

ui/components/Filters/index.js
ui/components/Layout/index.js
ui/components/Layout/style.module.scss
ui/components/PhaseBanner/index.js
ui/components/PhaseBanner/style.module.scss
ui/components/Search/style.module.scss
ui/cypress/e2e/home.cy.js
ui/cypress/e2e/standards/list.cy.js
ui/cypress/e2e/standards/standard-page.cy.js
ui/cypress/support/custom.js
ui/cypress/support/e2e.js
ui/package-lock.json
ui/package.json
ui/styles/Home.module.scss

* adds some additional tests for accessibility, using my [port of the cypress-axe package](https://www.npmjs.com/package/@-ralph/cypress-axe)
* Reorders headings in search page 
* One of our a11y failures was that the `phaseBanner` was free floating
outside of a landmark pieces of html, e.g. `<header>` or `<main>`
* Here I'm moving the `<PhaseBanner>` into the `<main>` section in order that
screen readers know which part of the site it's in
https://dequeuniversity.com/rules/axe/4.4/region?application=axeAPI
* Also fixes a header bounce from the search styling — the header
maintains the same shape whether it has a search bar in it or not now
* consistent with the markup in e.g. test and trace https://enquiries.test-and-trace.nhs.uk/national-guidance?t=1659096472610 
* adds a fix (and a …

[STAN-829] add some automated accessibility tests

---

ui/components/Dataset/index.js
ui/context/content.js

* Stops using `Snippet`, which was generating odd markup `<h3 id="resultSummary" data-loading="false"><span index="0" node="[object Object]">29 results</span></h3>`
* Remove call to content context
* add `role="status"` to results count span

[STAN-738] give role=status to results span

---

ui/pages/standards/index.js

Responding to concerns in our accessibility review that the current heading is not descriptive.
> The heading ‘Published standards’ does not provide enough descriptive information to convey the purpose of the content it is introducing.
> “While exploring the heading structure of the page using the Quick Nav ‘h’ command, I observed that although the filters were provided with their own heading, the search feature itself was not introduced in this way.

[STAN-739] add description to browse heading

---

ui/helpers/api.js

Upcoming standards are for the roadmap and should be filtered from the main list of published standards. This code exists in roadmap branch, but needs to be pushed first as data now includes unpublished standards

removed upcoming standards

---

ui/components/Analytics/index.js
ui/components/Analytics/style.module.scss
ui/components/Cookies/index.js
ui/components/Layout/index.js
ui/components/index.js
ui/helpers/gtag.js
ui/package-lock.json
ui/package.json

Google analytics is initialised on page load, but it requires a `localConsent` cookie in order to start logging to our google tag container.
Additional tracking cookie set
Showing consent being set and pageview events firing

[STAN-869] Add google analytics

---

ui/components/Pagination/index.js
ui/context/query.js

* Next.js doesn't handle key[]=a,key[]=b formatting from qs.stringify, it requries arrays to be in the format key=a,key=b
* Updated pagination to generate href in correct format (using object href)
* Updated pagination to use ajax progressive enhancement
* Updated query string helper to use URLSearchParams in place of qs.stringify

Bugfix - query string expected in different format

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml

* We build a docker image for each deployment again
* This is so we can set different build args for each environment
* this allows different analytics ids per env
* docker image tags reference their environment e.g.
```
IMAGE_TAG: ui-production-${{ github.sha }}
```

[STAN-869] Add in Analytics tags for test and prod builds

---

.github/workflows/build-and-test.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-test.yml

NB: we should just reference the integration test workflow from our deploy workflows in the future

update post-deploy integration tests to match other integration tests

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml
.github/workflows/helm-deploy-ui.yml

* Pulls out the yaml from each workflow and sections off to a reusable one for deploying the UI
* also resets our workflow operations to go sequentially through test => dev => test => prod
* we're still building and pulling a docker image in each job, in a subsequent PR I'll look into minimising the docker operations

[STAN-940] Add reusable workflow for deploying the UI

---

.github/workflows/build-and-test.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml
.github/workflows/integration-test.yml

* We call integration test in 4 places, (deploy dev, test, prod, build-and-test)
* Move it to a single configurable file
* call it! 
* Set the `pages_ckan_url` appropriately per env (hint: they're all pointing at prod now)

[STAN-938] Add independent integration test workflow, point pages url at prod

---

ui/components/Dataset/index.js
ui/context/query.js
ui/cypress/e2e/standards/list.cy.js

* Updated dataset logic to use a pageLoaded flag in place of the query comparison. This was failing to pick up when filters were removed
* Updated query builder to reset page when something other than page is changed

Bugfix - filters

---

ui/components/Search/style.module.scss

* Added custom override to stop search disappearing on mobile. This is only desired behaviour when search is in the header element

Bugfix - search disappears on mobile

---

reader/lib/write/index.js
reader/write-json-to-ckan.js

Having nuked my local CKAN setup this was very useful for importing all records from production to local
* extends write-location option: `'-w, --write-location <local|dev|test|prod>',`
* updates `owner_org` to use the org name, as the id was different and wouldn't allow for a successful write
* Makes the output a bit louder just in case you don't want to check the final log

Add "local" as an option for dataset imports

---

.github/workflows/integration-test.yml
.github/workflows/lighthouse-test.yml

* see https://github.com/foo-software/lighthouse-check-action
* adds an automated check of page quality using google lighthouse / https://web.dev/measure/
* only checks the homepage but can be run against multiple locations in the future
* can be modified to include minimum scores which we can fail on
* should notify us in slack on failure
**Artefacts uploaded on run:**
**Slack notifications:**

Add automated lighthouse tests

---

Dockerfile-ckan

* Adds our newly minted NHS theme plugin to our ckan deploys
* So far it's an exact replica of the base theme with the [addition of a noindex meta tag](https://github.com/Marvell-Consulting/ckanext-nhs-theme/blob/main/ckanext/nhs_theme/templates/base.html#L27)

[STAN-959] Add the NHS theme plugin to ckan

---

ui/components/TableOfContents/index.js
ui/components/TableOfContents/style.module.scss
ui/cypress/e2e/static-page.cy.js

* Added a11y to test a static page - regression for header search input label
* Reformatted TOC list to valid HTML - <ul> cannot be a child of <ul>

Bugfix - nested lists

---

ui/components/Layout/index.js
ui/pages/[page].js

[STAN-1059] meta descriptions from ckan

---

ui/components/Dataset/index.js
ui/components/Tag/index.js
ui/schema/index.js

- Updates our colour mappings for new status types
- draft is still mapped just in case we have some stragglers
- Redid the status formatting to sentence case values
NB: we'll need to update `What this status means` too

[STAN-1075] Update tag colour mappings

---

ui/pages/current-standards/[id].js

A simple change that passes through a standard's description to the Page component, rendering descriptions into a meta tag when available:

[STAN-997] Add meta descriptions to standards id pages

---

ui/components/DatasetSchema/index.js
ui/components/index.js
ui/pages/current-standards/[id].js

See https://schema.org/Dataset for more
* produces a json/ld representation of a standard in the `<head>` of the document
For this page, https://data.standards.nhs.uk/current-standards/national-cancer-waiting-times-monitoring-data-set
Tested using https://validator.schema.org/

[STAN-981] Add schema.org annotations to standards

---

ui/components/DatasetSchema/index.js
ui/components/Page/index.js
ui/components/index.js
ui/context/content.js
ui/cypress/e2e/schema.org.cy.js
ui/helpers/getHost.js
ui/helpers/getPageProps.js
ui/pages/[page].js
ui/pages/current-standards/index.js
ui/pages/future-standards.js
ui/pages/index.js
ui/pages/search-results.js
ui/pages/site-map.js

In addition to DataSet schema annotations for individual standards pages, this introduces basic WebPage schemas for all pages. This includes a `contactPoint` and the page description.
```js
{ 
'@context': 'https://schema.org/',
'@type': 'WebPage',
contactPoint: {
'@type': 'ContactPoint',
email: 'england.interop.standards@nhs.net',
},
title: 'Help and resources',
description:
'Explore resources for the data standards community in health and social care including links to discussion forums and government regulations.',
url: {BASE_URL}/help-and-resources
}
```

[STAN-978] Add WebPage schema to all pages

---

ui/pages/future-standards.js

The email link on the future standards page exists but is _**not linked!**_
Regard the sorry state of the email address, lurking like so much unadorned hypertext flotsam free floating in cyberspace
Experience the updated functionality of a comprehensively linked email address in our digital estate.
**Featuring:**
* classic blue text colour 
* classic blue underline as text decoration
* a functioning "mailto" destination which matches that which is visually presented
* 100% guaranteed conversion rate between clicks to emails sent

[STAN-1031] link the email on future standards

---

ui/pages/future-standards.js

The `query` object should be a property of the first argument to `getPageProps`. Passing the query as it was means it is ignored by the `list` function and therefore returns all standards rather than only incative on initial page load.

Send correct argument structure to `getPageProps` function

---

Dockerfile-ckan

I've pushed two new schemas to the Marvell fork of [ckanext-scheming](https://github.com/Marvell-Consulting/ckanext-scheming/commits/master). 
This change allows us to push our own changes without fear of the example schemas being overriden by merges from the upstream ckan-scheming project.
Should've done this ages ago!

use our own versions of dataset and org schemas

---

ui/components/Page/index.js

https://developers.google.com/search/docs/appearance/snippet#use-quality-descriptions
We accidentally added 'value', which is normal for meta tags, but 'content' is expected by google et al

STAN-1097 "content" not "value" in meta descriptions

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml
charts/ckan/values.yaml

- Sets password protection to `true`
- Adds password passthrough into all deployments
- values.yaml should now receieve redis password values
- A value for `REDIS_PASSWORD` has been added to all environments

[STAN-1107] Add password auth to Redis

---

ui/Dockerfile

* Previously we weren't declaring a USER in our UI build, meaning root was left available
* This changes the build to run using the `node` user

[STAN-1110] set USER to node in ui Dockerfile

---

ui/Dockerfile

Deploy dev fails with an EACCESS issue for creating `node_modules`: https://github.com/nhsx/standards-registry/actions/runs/3409968479/jobs/5672369479#step:6:64
This creates and `chown`s the `node_modules` folder before running the usual installation steps

[STAN-1110] always create node_modules

---

ui/components/Cookies/index.js
ui/components/Pagination/index.js
ui/cypress/e2e/standards/list.cy.js
ui/helpers/api.js

Also some 🏡🧹
* adds `alertdialog` role to cookie banner callout
* gives cookie banner a readable aria label
* adds a11y check to listings page with a content check before injecting the checker (stops race conditions)
* Adds full console error for api request failures

[STAN-1047] Add aria current=page to pagination

---

ui/pages/index.js
ui/pages/published-standards/index.js
ui/pages/search-results.js

* Avoids reflow issues for people using highly magnified version of the page

[STAN-737] shorter placeholder text

---

ui/components/Page/index.js

In order to indicate to search engines (and users!) that we're in a different view onto published standards content, we're here taking the first care setting/topic filter and appending it to the title.
In the case of multiple topics/care settings, we will still just take the first value as a compromise between being completist and coherent.

[STAN-1077] honour first value of query in titles

---

ui/components/Dataset/index.js
ui/components/ResponsiveTable/index.js
ui/cypress/e2e/home.cy.js
ui/pages/future-standards.js

We've been getting consistent warnings about dependencies in `useEffect`, so here I'm adding them in to the dependency array.
More on this here:
https://github.com/facebook/react/issues/14920
Should quieten warnings. Features still work too, which is nice 😎

Quieten various lint warnings

---

ui/next.config.js

Passes back a 308 on requests to `current-standards` and any nested path:
```
❯ curl http://localhost:3000/current-standards -v
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /current-standards HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 308 Permanent Redirect
< Location: /published-standards
< Refresh: 0;url=/published-standards
< Date: Tue, 15 Nov 2022 09:52:21 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
/published-standards%                                                                                                                             
```
and for …

[STAN-1180] add permanent redirect from 'current-standards' to 'published-standards'

---

ui/pages/index.js

It was missing an `s` so was throwing an error

Fix link to Record standards

---

reader/.eslintrc.cjs
reader/.prettierignore
reader/.prettierrc
reader/lib/migrations/21-nov-2022-string-to-boolean/__test__/fixtures/standard-fixture.js
reader/lib/migrations/21-nov-2022-string-to-boolean/__test__/index.test.js
reader/lib/migrations/21-nov-2022-string-to-boolean/index.js
reader/lib/write/index.js
reader/write-json-to-ckan.js

A quick migrations update which also enables the passing of arbitrary api keys, rather than locally configured ones:
```
CKAN_KEY={myApiKey} && node write-json-to-ckan.js --from \
'https://2gv8f9zmci.execute-api.eu-west-2.amazonaws.com/dev/get?key=$CKAN_KEY&env=https://manage.standards.nhs.uk/api/action' \
--write-location prod --key=$CKAN_KEY
```
Note: this has now been run on all envs and should have set "false" and "true" strings to their corresponding booleans

[STAN-1196] migration: set strings to booleans

---

.github/workflows/build-and-test.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml

* I've pushed up all symbolic refs in git from `master` to `main`
* Settings have been updated to using `main` as the default branch
* this PR also updates all internal workflow references from `master` to `main`

[STAN-1095] Switch all master references to main in workflows
